In [2]:
import pandas as pd
import numpy as np

In [2]:
#3-dimensional vector in numpy
a = np.zeros((2, 3, 4))
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [3]:
# Declaring Vectors

x = [1, 2, 3]
y = [4, 5, 6]

print(type(x))

# This does'nt give the vector addition.
print(x + y)

# Vector addition using Numpy

z = np.add(x, y)
print(z)
print(type(z))

# Vector Cross Product
mul = np.cross(x, y)
print(mul)

<class 'list'>
[1, 2, 3, 4, 5, 6]
[5 7 9]
<class 'numpy.ndarray'>
[-3  6 -3]


## Notation
<img src='http://s8.picofile.com/file/8349058626/la.png'>

# Subtraction and Addition of Metrices

In [47]:
print("np.arange(9):", np.arange(9))
print("np.arange(9, 18):", np.arange(9, 18))

A = np.arange(9, 18).reshape((3, 3))
B = np.arange(9).reshape((3, 3))

print("A:", A)
print("B:", B)

np.arange(9): [0 1 2 3 4 5 6 7 8]
np.arange(9, 18): [ 9 10 11 12 13 14 15 16 17]
A: [[ 9 10 11]
 [12 13 14]
 [15 16 17]]
B: [[0 1 2]
 [3 4 5]
 [6 7 8]]


We can now add and subtract the two matrices $A$ and $B$:

In [48]:
A + B

array([[ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [49]:
A - B

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

## Matrix Multiplication
<img src='https://www.mathsisfun.com/algebra/images/matrix-multiply-constant.gif'>

The result of the multiplication of two matrixes $A \in \mathbb{R}^{m \times n}$ and $B \in \mathbb{R}^{n \times p}$ is the matrix:

In [470]:
# initializing matrices 
x = np.array([[1, 2], [4, 5]]) 
y = np.array([[7, 8], [9, 10]])

The number of columns in $A$ must be equal to the number of rows in $B$.

In [6]:
# using divide() to divide matrices 
print ("The element wise division of matrix is : ") 
print (np.divide(x,y)) 

The element wise division of matrix is : 
[0.25 0.4  0.5 ]


In [7]:
# using multiply() to multiply matrices element wise 
print ("The element wise multiplication of matrix is : ") 
print (np.multiply(x,y))

The element wise multiplication of matrix is : 
[ 4 10 18]


## Vector-Vector Products
numpy.cross(a, b, axisa=-1, axisb=-1, axisc=-1, axis=None)
Return the cross product of two (arrays of) vectors.

In [3]:
x = [1, 2, 3]
y = [4, 5, 6]
np.cross(x, y)

array([-3,  6, -3])

We can now calculate the $dot$ or $inner product$ using the *dot* function of *numpy*:

In [4]:
np.dot(x, y)

32

The order of the arguments is irrelevant:

In [5]:
np.dot(y, x)

32

In fact, in our understanding of Linear Algebra, we take the arrays above to represent **row vectors**. *Numpy* treates them differently.

We see the issues when we try to transform the array objects. Usually, we can transform a row vector into a column vector in *numpy* by using the *T* method on vector or matrix objects:

In [13]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])

print("x:", x)
print("y:", y)
print("xT:", x.T)
print("yT:", y.T)

x: [1 2 3 4]
y: [5 6 7 8]
xT: [1 2 3 4]
yT: [5 6 7 8]


The problem here is that this does not do, what we expect it to do. It only works, if we declare the variables not to be arrays of numbers, but in fact a matrix:

In [7]:
x = np.array([[1, 2, 3, 4]])
y = np.array([[5, 6, 7, 8]])
print("x:", x)
print("y:", y)
print("xT:", x.T)
print("yT:", y.T)


x: [[1 2 3 4]]
y: [[5 6 7 8]]
xT: [[1]
 [2]
 [3]
 [4]]
yT: [[5]
 [6]
 [7]
 [8]]


Note that the *numpy* functions *dot* and *outer* are not affected by this distinction. We can compute the dot product using the mathematical equation above in *numpy* using the new $x$ and $y$ row vectors:

In [8]:
print("x:", x)
print("y:", y.T)
np.dot(x, y.T)

x: [[1 2 3 4]]
y: [[5]
 [6]
 [7]
 [8]]


array([[70]])

Or by reverting to:

In [9]:
print("x:", x.T)
print("y:", y)
np.dot(y, x.T)

x: [[1]
 [2]
 [3]
 [4]]
y: [[5 6 7 8]]


array([[70]])

To read the result from this array of arrays, we would need to access the value this way:

In [17]:
np.dot(y, x.T)[0][0]

70

## Outer Product of Two Vectors
Compute the outer product of two vectors.

In [18]:
x = np.array([[1, 2, 3, 4]])
print("x:", x)
print("xT:", np.reshape(x, (4, 1)))
print("xT:", x.T)
print("xT:", x.transpose())

x: [[1 2 3 4]]
xT: [[1]
 [2]
 [3]
 [4]]
xT: [[1]
 [2]
 [3]
 [4]]
xT: [[1]
 [2]
 [3]
 [4]]


We can now compute the **outer product** by multiplying the column vector $x$ with the row vector $y$:

In [19]:
x = np.array([[1, 2, 3, 4]])
y = np.array([[5, 6, 7, 8]])
x.T * y

array([[ 5,  6,  7,  8],
       [10, 12, 14, 16],
       [15, 18, 21, 24],
       [20, 24, 28, 32]])

*Numpy* provides an *outer* function that does all that:

In [20]:
np.outer(x, y)

array([[ 5,  6,  7,  8],
       [10, 12, 14, 16],
       [15, 18, 21, 24],
       [20, 24, 28, 32]])

Note, in this simple case using the simple arrays for the data structures of the vectors does not affect the result of the *outer* function:

In [21]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
np.outer(x, y)

array([[ 5,  6,  7,  8],
       [10, 12, 14, 16],
       [15, 18, 21, 24],
       [20, 24, 28, 32]])

<a id="43"></a> <br>
## Matrix-Vector Products
Use numpy.dot or a.dot(b). See the documentation [here](http://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html).

In [22]:
a = np.array([[ 5, 1 ,3], [ 1, 1 ,1], [ 1, 2 ,1]])
b = np.array([1, 2, 3])
print (a.dot(b))

[16  6  8]


Using *numpy* we can compute $Ax$:

In [23]:
A = np.array([[4, 5, 6],
             [7, 8, 9]])
x = np.array([1, 2, 3])
A.dot(x)

array([32, 50])

## Matrix-Matrix Products

In [24]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.matmul(a, b)

array([[4, 1],
       [2, 2]])

In [25]:
matrix1 = np.matrix(a)
matrix2 = np.matrix(b)

In [26]:
matrix1 + matrix2

matrix([[5, 1],
        [2, 3]])

In [27]:
matrix1 - matrix2

matrix([[-3, -1],
        [-2, -1]])

###  Multiplication

In [28]:
np.dot(matrix1, matrix2)

matrix([[4, 1],
        [2, 2]])

In [29]:
matrix1 * matrix2

matrix([[4, 1],
        [2, 2]])

## Identity Matrix

numpy.identity(n, dtype=None)

Return the identity array.

In [30]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

How to create *identity matrix* in *numpy*  

In [31]:
identy = np.array([[21, 5, 7],[9, 8, 16]])
print("identy:", identy)

identy: [[21  5  7]
 [ 9  8 16]]


In [32]:
identy.shape

(2, 3)

In [33]:
np.identity(identy.shape[1], dtype="int")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [34]:
np.identity(identy.shape[0], dtype="int")

array([[1, 0],
       [0, 1]])

###  Inverse Matrices

In [35]:
inverse = np.linalg.inv(matrix1)
print(inverse)

[[1. 0.]
 [0. 1.]]


## Diagonal Matrix

In *numpy* we can create a *diagonal matrix* from any given matrix using the *diag* function:

In [36]:
import numpy as np
A = np.array([[0,   1,  2,  3],
              [4,   5,  6,  7],
              [8,   9, 10, 11],
              [12, 13, 14, 15]])
np.diag(A)

array([ 0,  5, 10, 15])

In [37]:
np.diag(A, k=1)

array([ 1,  6, 11])

In [38]:
np.diag(A, k=-1)

array([ 4,  9, 14])

## Transpose of a Matrix

In [39]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [40]:
a.transpose()

array([[1, 3],
       [2, 4]])

## Symmetric Matrices
In linear algebra, a symmetric matrix is a square matrix that is equal to its transpose. Formally,
<img src='https://wikimedia.org/api/rest_v1/media/math/render/svg/ad8a5a3a4c95de6f7f50b0a6fb592d115fe0e95f'>


In [42]:
N = 100
b = np.random.randint(-2000,2000,size=(N,N))
b_symm = (b + b.T)/2

## The Trace
Return the sum along diagonals of the array.

In [43]:
np.trace(np.eye(3))

3.0

In [44]:
print(np.trace(matrix1))

2


In [45]:
det = np.linalg.det(matrix1)
print(det)

1.0


# Linear Independence and Rank
How to identify the linearly independent rows from a matrix?

In [46]:
#How to find linearly independent rows from a matrix
matrix = np.array(
    [
        [0, 1 ,0 ,0],
        [0, 0, 1, 0],
        [0, 1, 1, 0],
        [1, 0, 0, 1]
    ])

lambdas, V =  np.linalg.eig(matrix.T)
# The linearly dependent row vectors 
print (matrix[lambdas == 0,:])

[[0 1 1 0]]


## Inverse
We use numpy.linalg.inv() function to calculate the inverse of a matrix. The inverse of a matrix is such that if it is multiplied by the original matrix, it results in identity matrix.[tutorialspoint](https://www.tutorialspoint.com/numpy/numpy_inv.htm)

In [50]:
x = np.array([[1,2],[3,4]]) 
y = np.linalg.inv(x) 
print (x )
print (y )
print (np.dot(x,y))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


## Range and Nullspace of a Matrix

In [51]:
from scipy.linalg import null_space
A = np.array([[1, 1], [1, 1]])
ns = null_space(A)
ns * np.sign(ns[0,0])  # Remove the sign ambiguity of the vector

array([[ 0.70710678],
       [-0.70710678]])

# Determinant
Compute the determinant of an array

In [52]:
a = np.array([[1, 2], [3, 4]])
np.linalg.det(a)

-2.0000000000000004

### Create a dense meshgrid

In [55]:
np.mgrid[0:5,0:5]

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

### Permute array dimensions

In [56]:
a=np.array([1,2,3])
b=np.array([(1+5j,2j,3j), (4j,5j,6j)])
c=np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]])

In [57]:
np.transpose(b)

array([[1.+5.j, 0.+4.j],
       [0.+2.j, 0.+5.j],
       [0.+3.j, 0.+6.j]])

In [58]:
b.flatten()

array([1.+5.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j, 0.+6.j])

In [59]:
np.hsplit(c,2)

[array([[[1.5, 2. , 3. ]],
 
        [[3. , 2. , 1. ]]]),
 array([[[4., 5., 6.]],
 
        [[4., 5., 6.]]])]