# 13. NumPy – Array Manipulation

## numpy.reshape
This function gives a new shape to an array without changing the data. It accepts the following parameters: \
numpy.reshape(arr, newshape, order')

In [3]:
import numpy as np
a = np.arange(8)

print(a)

b = a.reshape(4,2)
b

[0 1 2 3 4 5 6 7]


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

# numpy.ndarray.flat
This function returns a 1-D iterator over the array. It behaves similar to Python's built-in
iterator.

In [7]:
import numpy as np
a = np.arange(8).reshape(2,4)

print(a)

print('After applying the flat function:')
# returns element corresponding to index in flattened array
print(a.flat[5])

[[0 1 2 3]
 [4 5 6 7]]
After applying the flat function:
5


## numpy.ndarray.flatten
This function returns a copy of an array collapsed into one dimension. The function takes
the following parameters.

ndarray.flatten(order)

In [8]:
import numpy as np
a = np.arange(8).reshape(2,4)

print(a)

print('After applying the flatten function:')
# returns element corresponding to index in flattened array
print(a.flatten())

[[0 1 2 3]
 [4 5 6 7]]
After applying the flatten function:
[0 1 2 3 4 5 6 7]


## numpy.ravel
This function returns a flattened one-dimensional array. A copy is made only if needed.
The returned array will have the same type as that of the input array. The function takes
one parameter.

numpy.ravel(a, order)

In [10]:
import numpy as np
a = np.arange(8).reshape(2,4)

print(a)

print('After applying the ravel function:')
# returns element corresponding to index in flattened array
print(a.ravel())

[[0 1 2 3]
 [4 5 6 7]]
After applying the ravel function:
[0 1 2 3 4 5 6 7]


# numpy.transpose

In [13]:
a, np.transpose(a) , a.T

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[0, 4],
        [1, 5],
        [2, 6],
        [3, 7]]),
 array([[0, 4],
        [1, 5],
        [2, 6],
        [3, 7]]))

## numpy.expand_dims
This function expands the array by inserting a new axis at the specified position. Two
parameters are required by this function.

numpy.expand_dims(arr, axis)

In [14]:
x = np.array(([1,2],[3,4]))
x

array([[1, 2],
       [3, 4]])

In [15]:
y = np.expand_dims(x, axis=0)
y

array([[[1, 2],
        [3, 4]]])

In [16]:
x.shape, y.shape

((2, 2), (1, 2, 2))

In [17]:
y = np.expand_dims(x, axis=1)
y

array([[[1, 2]],

       [[3, 4]]])

In [18]:
x.shape, y.shape

((2, 2), (2, 1, 2))

In [19]:
x.ndim,y.ndim

(2, 3)

# numpy.squeeze
This function removes one-dimensional entry from the shape of the given array. Two
parameters are required for this function.

numpy.squeeze(arr, axis)

In [20]:
import numpy as np
x = np.arange(9).reshape(1,3,3)
x

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [21]:
y = np.squeeze(x)
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
x.shape, y.shape

((1, 3, 3), (3, 3))

In [23]:
x.ndim,y.ndim

(3, 2)

## numpy.concatenate
Concatenation refers to joining. This function is used to join two or more arrays of the
same shape along a specified axis. The function takes the following parameters.

numpy.concatenate((a1, a2, ...), axis)

In [24]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [25]:
b = np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [26]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [27]:
np.concatenate((a,b),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## numpy.stack
This function joins the sequence of arrays along a new axis. This function has been added
since NumPy version 1.10.0. Following parameters need to be provided.

numpy.stack(arrays, axis)

In [28]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [29]:
b = np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [30]:
np.stack((a,b),0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [31]:
np.stack((a,b),1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

## numpy.split
This function divides the array into subarrays along a specified axis. The function takes
three parameters.

numpy.split(ary, indices_or_sections, axis)

In [33]:
a = np.arange(9)

b = np.split(a,3)

a,b

In [35]:
b = np.split(a,[4,7])
b

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]

## numpy.append
This function adds values at the end of an input array. The append operation is not in-
place, a new array is allocated. Also the dimensions of the input arrays must match
otherwise ValueError will be generated.
The function takes the following parameters.

numpy.append(arr, values, axis)

In [36]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
np.append(a, [7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.append(a, [[7,8,9]],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
np.append(a, [[5,5,5],[7,8,9]],axis=1)

array([[1, 2, 3, 5, 5, 5],
       [4, 5, 6, 7, 8, 9]])

# 14. NumPy − Mathematical Functions

## Trigonometric Functions
NumPy has standard trigonometric functions which return trigonometric ratios for a given
angle in radians.

In [42]:
import numpy as np
a = np.array([0,30,45,60,90])

print('Sine of different angles:')
# Convert to radians by multiplying with pi/180
print(np.sin(a*np.pi/180))

print('\n')
print('Cosine values for angles in array:')
print(np.cos(a*np.pi/180))

Sine of different angles:
[0.         0.5        0.70710678 0.8660254  1.        ]


Cosine values for angles in array:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


## numpy.around()
This is a function that returns the value rounded to the desired precision. The function
takes the following parameters.

numpy.around(a,decimals)

In [43]:
a = np.array([1.0,5.55, 123, 0.567, 25.532])
a

array([  1.   ,   5.55 , 123.   ,   0.567,  25.532])

In [47]:
np.around(a)

array([  1.,   6., 123.,   1.,  26.])

In [48]:
np.around(a, decimals=1)

array([  1. ,   5.6, 123. ,   0.6,  25.5])

In [49]:
np.around(a, decimals=-1)

array([  0.,  10., 120.,   0.,  30.])

## numpy.floor()

In [51]:
np.floor(a)

array([  1.,   5., 123.,   0.,  25.])

In [52]:
np.ceil(a)

array([  1.,   6., 123.,   1.,  26.])

# 15. NumPy − Arithmetic Operations

np. + - / *


numpy.reciprocal()

numpy.power()

numpy.mod()



# 16. NumPy − Statistical Functions

## numpy.amin() and numpy.amax()
These functions return the minimum and the maximum from the elements in the given
array along the specified axis.

In [53]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]])
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [54]:
np.amin(a,1)

array([3, 3, 2])

In [55]:
np.amin(a,0)

array([2, 4, 3])

In [56]:
np.amax(a, axis=0)

array([8, 7, 9])

# numpy.median()

In [57]:
np.median(a)

4.0

In [58]:
np.median(a, axis=0)

array([3., 4., 5.])

In [59]:
np.median(a, axis=1)

array([5., 4., 4.])

## numpy.mean()

## numpy.average()

# 17. NumPy − Sort, Search & Counting Functions

## numpy.sort()
The sort() function returns a sorted copy of the input array. It has the following
parameters:
    
numpy.sort(a, axis, kind, order)

In [60]:
a = np.array([[3,7],[9,1]])
a

array([[3, 7],
       [9, 1]])

In [61]:
np.sort(a)

array([[3, 7],
       [1, 9]])

In [62]:
# Order parameter in sort function
dt = np.dtype([('name', 'S10'),('age', int)])
a = np.array([("raju",21),("anil",25),("ravi", 17), ("amar",27)], dtype=dt)
a

array([(b'raju', 21), (b'anil', 25), (b'ravi', 17), (b'amar', 27)],
      dtype=[('name', 'S10'), ('age', '<i8')])

In [63]:
np.sort(a, order='name')

array([(b'amar', 27), (b'anil', 25), (b'raju', 21), (b'ravi', 17)],
      dtype=[('name', 'S10'), ('age', '<i8')])

# 18. NumPy − Linear Algebra

## numpy.dot()
This function returns the dot product of two arrays. For 2-D vectors, it is the equivalent to
matrix multiplication. For 1-D arrays, it is the inner product of the vectors. For N-
dimensional arrays, it is a sum product over the last axis of a and the second-last axis
of b.



In [64]:
import numpy.matlib
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])

np.dot(a,b)

array([[37, 40],
       [85, 92]])

## numpy.inner()
This function returns the inner product of vectors for 1-D arrays. For higher dimensions,
it returns the sum product over the last axes

In [65]:
import numpy as np
np.inner(np.array([1,2,3]),np.array([0,1,0]))
# Equates to 1*0+2*1+3*0

2

## numpy.matmul()
The numpy.matmul() function returns the matrix product of two arrays. While it returns
a normal product for 2-D arrays, if dimensions of either argument is >2, it is treated as a
stack of matrices residing in the last two indexes and is broadcast accordingly.

In [66]:
a = [[1,0],[0,1]]
b = [[4,1],[2,2]]

np.matmul(a,b)

array([[4, 1],
       [2, 2]])

## Determinant

In [67]:
np.linalg.det(a)

1.0

In [68]:
np.linalg.det(b)

6.0